project:
  type: website
  output-dir: docs

website:
  title: "Yousif Najat"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: dataviz.qmd
        text: Data Viz

format:
  html:
    theme:
      - flatly
      - brand
    css: styles.css
    toc: true
    page-layout: full



