project:
  type: website
  output-dir: docs

website:
  title: "Yousif Najat"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - text: Data Viz
        menu:
          - text: "Pell Grant"
            href: pellgrant.html

format:
  html:
    theme:
      - flatly
      - brand
    css: styles.css
    toc: true
    page-layout: full



