---
title: "Analysis of Pell Grant Recipients Over Time for Selected Liberal Arts Colleges"
author: Yousif Najat
date: September 29, 2026
format: 
    html:
      code-fold: true
      code-summary: "Code"
toc: false
execute: 
  warning: false
  message: false
---

## Background & Data

Pell grants are a form of need-based financial aid provided by the U.S. federal government to undergraduate students, and do not need to be repaid by awarded undergraduates. The Pell Grant dataset--compiled by the U.S. Department of Education--provides data on the total number of Pell Grant recipients at U.S. colleges/universities and amount of total aid awarded at U.S. colleges/universities from 1990 to 2017.

## Data Visualization

```{r}
#| fig-width: 11
#| fig-height: 8


library(tidyverse)

pell <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/main/data/2022/2022-08-30/pell.csv')

liberal_arts_pell <- pell |> 
    filter(NAME %in% c(
    "Pomona College", 
    "Williams College", 
    "Amherst College", 
    "Bowdoin College", 
    "Claremont Mckenna College", 
    "Swarthmore College", 
    "Harvey Mudd College", 
    "Wellesley College", 
    "Scripps College", 
    "Pitzer College", 
    "Haverford College", 
    "Middlebury College")
    )


pellgrant_viz <- liberal_arts_pell |> 
    ggplot(aes(x = YEAR, y = RECIPIENT)) +
    geom_point() +
    geom_line() +
    facet_wrap(~NAME) +
    theme_light() +
    labs(
        title = "Number of Pell Grant Recipients Over Time", 
        subtitle = "For Selected Top Liberal Arts Colleges.", 
        x = "Year",
        y = "Pell Grant Recipients"
        ) +
    theme(
        plot.title = element_text(face = "bold", size = 16), 
        plot.subtitle = element_text(size = 11), 
        axis.title = element_text(face = "bold"),
        strip.background = element_rect(fill = "white", color = "black", linewidth = 1),
        strip.text = element_text(face = "bold", color = "black"), 
        axis.text.x = element_text(face = "bold", angle = 45, hjust = 1),
        axis.text.y = element_text(face = "bold"),
        panel.border = element_rect(color = "black", fill = "", linewidth = 1)
        )

pellgrant_viz

```

From the visualization above, we observe that Claremont McKenna College, Scripps College, and Harvey Mudd College maintained a low and relatively constant number of Pell Grant recipients. In contrast, the number of Pell Grant recipients at Amherst College, Middlebury College, Pomona College, and Williams College increased gradually over time. Additionally, while the other selected liberal arts colleges had either relatively constant or increasing numbers of Pell Grant recipients from 1990 to 2017, Pitzer College experienced a decrease in the number of Pell Grant recipients from 1990 to 2017.

## Data Source

The Pell Grant data used in this vizualization was provided by TidyTuesday as part of the **August 30, 2022 TidyTuesday dataset**, and can be accessed [here](https://github.com/rfordatascience/tidytuesday/tree/main/data/2022/2022-08-30). According to TidyTuesday, the Pell Grant data was obtained originally from the U.S. Department of Education.